name: e2e test
on:
  pull_request:
    branches:
     - main
  push:
    branches:
     - main
     - cleanup_oras_v1

jobs:
  e2e:
    name: e2e test
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
  
      - name: Prepare the test oci registry
        run: |
          ./scripts/reg.sh
          ./scripts/e2e_prepare.sh

      - name: run e2e
        run: |
          make e2e
